services:
  cassandra:
    image: 'cassandra:latest'
    ports:
      - '9042:9042'
    environment:
      - 'CASSANDRA_DC=datacenter1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
